# Built from native speakers, with inspiration from
# https://github.com/zacanger/profane-words
# and
# https://github.com/thisandagain/washyourmouthoutwithsoap/blob/develop/data/build.json
# and
# https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words


english_flagged_words = [
    "anal",
    "bareback",
    "bbw",
    "bdsm",
    "blowjob",
    "blowjobs",
    "brazzers",
    "bukkake",
    "camgirl",
    "camwhore",
    "cocksucking",
    "cougar",
    "creampie",
    "cuckold",
    "cum",
    "cumming",
    "cums",
    "cumshot",
    "cumshots",
    "cumslut",
    "cunnilingus",
    "deepthroat",
    "deepthroating",
    "dildo",
    "dildos",
    "dogging",
    "doggystyle",
    "dominatrix",
    "erotic",
    "fellatio",
    "femdom",
    "fingering",
    "fisting",
    "footjob",
    "gangbang",
    "handjob",
    "hentai",
    "horney",
    "horniest",
    "horny",
    "jism",
    "jizz",
    "masterbating",
    "masturbate",
    "masturbating",
    "masturbation",
    "milf",
    "orgies",
    "orgy",
    "pegging",
    "porn",
    "pornhub",
    "porno",
    "pornos",
    "pornstar",
    "pornstars",
    "redtube",
    "rimming",
    "slutty",
    "squirting",
    "strapon",
    "threesome",
    "vibrator",
    "xhamster",
    "xnxx",
    "xvideos",
    "xxx",
    "youporn",
    "slot",
    "wallet",
]


flagged_words = {
    "ar": english_flagged_words
    + [
        "إباحي",
        "احتلام",
        "است",
        "استمناء",
        "اغتصاب",
        "أورغازم",
        "إيروتيك",
        "أير",
        "بز",
        "بزاز",
        "بظر",
        "بورن",
        "بيضان",
        "مص",
        "ثدي",
        "جماع",
        "جنس",
        "حلمة",
        "خلاعة",
        "خنثي",
        "خول",
        "دعارة",
        "زب",
        "سحاق",
        "سحاقية",
        "سكس",
        "سيكس",
        "شاذ",
        "شبق",
        "شرج",
        "شرموطة",
        "شهواني",
        "شهوة",
        "طيز",
        "عادة السرية",
        "عاهرة",
        "عرص",
        "فاسقة",
        "فرج",
        "قحبة",
        "قضيب",
        "كس",
        "لحس",
        "لعق",
        "لواط",
        "لوطي",
        "مؤخرة",
        "متناك",
        "متناكة",
        "مومس",
        "مثير",
        "مص",
        "مضاجعة",
        "مفلقسة",
        "مني",
        "مهتاج",
        "نشوة",
        "نكاح",
        "نيك",
    ],
    "bn": english_flagged_words
    + [
        "আঙ্গুলি করা",
        "আচোদা",
        "খানকি",
        "খানকি মাগি",
        "গান্ড মারানো",
        "গুদ মারানি",
        "চুচুক",
        "চোদ",
        "চোদনা",
        "চোদা",
        "চোদা বোন",
        "চোদাচুদি",
        "জারজ",
        "নাঙ্গ",
        "নেংটা",
        "পর্ণহাব",
        "পর্ন",
        "পর্নস্টার",
        "পর্নোগ্রাফি",
        "পোঁদ",
        "পোঁদ মারানি",
        "পোদ মারানি",
        "বাঁড়া",
        "বানচোদ",
        "বেশ্যা",
        "বেশ্যার ছেলে",
        "বোকাচোদা",
        "ভগ",
        "মা চোদা",
        "মাগী",
        "মাদারচোদ",
        "মুখে নিবি",
        "মোরগ",
        "রেন্ডি",
        "শিশ্ন",
        "স্তন",
        "স্তনবৃন্ত",
        "হস্তমৈথুন",
    ],
    "ca": english_flagged_words
    + [
        "cagarro",
        "cagarros",
        "cipote",
        "cipotes",
        "collons",
        "colló",
        "consolador",
        "consoladors",
        "cony",
        "conys",
        "corre's",
        "corre't",
        "corregut",
        "cunillingus",
        "córrer-se",
        "escorreguda",
        "escorregudes",
        "escorregut",
        "escrot",
        "escrots",
        "escórre's",
        "escórre't",
        "escórrer-se",
        "mamada",
        "mamadera",
        "mamaderes",
        "mamades",
        "masturba",
        "masturbacions",
        "masturbació",
        "masturbant",
        "masturbar",
        "masturbar-se",
        "masturbat",
        "masturbats",
        "masturbes",
        "orgasme",
        "orgasmes",
        "ou",
        "ous",
        "palla",
        "palles",
        "pornografia",
        "semen",
        "semens",
        "verga",
        "vergues",
        "xxx",
    ],
    "en": english_flagged_words,
    "es": english_flagged_words
    + [
        "chupar el coño",
        "chupar la concha",
        "chupar la polla",
        "chupar la verga",
        "comer el coño",
        "comer la concha",
        "comer la polla",
        "comer la verga",
        "coprofagía",
        "correrse",
        "cunillingus",
        "fagging",
        "felación",
        "felching",
        "follada",
        "follador de culo",
        "folladores",
        "fudge packer",
        "hacer una paja",
        "hacerse una paja",
        "hore",
        "kock",
        "macizorra",
        "madre folladora",
        "mamada",
        "perro follador",
        "pisser",
        "pornografía",
        "sado",
        "sadomasoquismo",
        "sadomasoquista",
        "sexo anal",
        "skank",
        "smegma",
        "x clasificado",
    ],
    "eu": english_flagged_words + [],
    "fr": english_flagged_words
    + [
        "baiseurs",
        "baiseur",
        "baiseuse",
        "baiseuses",
        "branlette",
        "branlettes",
        "branleuse",
        "branleuses",
        "cunillingus",
        "cunilingus",
        "enculée",
        "enculées",
        "enculation",
        "enculations",
        "enculement",
        "enculements",
        "fellation",
        "fellations",
        "porno",
        "pornos",
        "pornographie",
        "pornographique",
        "pornographiques",
        "salope",
        "salopes",
        "suceuse",
        "suceuses",
        "xxx",
    ],
    "hi": english_flagged_words
    + [
        "अंडकोश की थैली",
        "एक्स रेटेड",
        "ओगाज़्म",
        "कामोद्दीपक चित्र",
        "कालीन का चूरा",
        "कून",
        "कॉक",
        "गेंद का थैला",
        "चाकलेट का रंग",
        "चूची",
        "चूतड़",
        "झटका बंद",
        "ठगना पैकर",
        "डिल्डो",
        "नितंब",
        "पिछाड़ी",
        "पीड़न कामुक",
        "पॉर्न",
        "फटना",
        "फूहड़",
        "बट",
        "बहुत मदहोश",
        "बेल अंत",
        "भगवान-शापित",
        "भगशेफ",
        "माँ कमीने",
        "मुखमैथुन",
        "मुर्गा चूसने वाला",
        "रक्तरंजित",
        "लेबिया",
        "वहशी",
        "वहशीता",
        "वैंग",
        "शिश्नमल",
        "संभोग सुख",
        "सह शॉट",
        "सींग का बना हुआ",
        "होर",
        "घपा घप",
        "चुदाई",
        "चुदक्कड़",
    ],
    "id": english_flagged_words
    + [
        "bokep",
        "coli",
        "colmek",
        "grepe",
        "horni",
        "janda",
        "jembut",
        "jilat memek",
        "jilmek",
        "kontol",
        "masturbasi",
        "memek",
        "ngentot",
        "ngewe",
        "peju",
        "pepek",
        "pornografi",
        "sange",
        "sepong",
        "tusbol",
        "kontol",
        "Bertingkat",
        "Pelacur",
        "pasta udang",
        "SAYA",
        "Kotoran",
        "kokang",
        "Cat",
        "penis",
        "Jake",
        "Jiao",
        "pelacur",
        "bikinan",
        "pantat",
        "air pecah",
        "Anda",
        "Persetan",
        "Brengsek",
        "Bersihkan kulkas",
        "tumit",
        "estrus",
        "menonjol",
        "Wanita jahat",
        "menuangkan",
        "Apa apaan",
        "Daging",
        "cat",
        "berengsek",
        "Omnokkha",
        "Kerbau",
        "ke jari"
        "Nilai X",
        "seks oral",
        "dasar",
        "Shock Off",
        "dildo",
        "Randy"
        "Pelacur",
        "pemalu"
        "sadisme",
        "Bom seks",
        "seksi",
        "pornografi",
        "Lin",
        "ayam",
        "pengisap ayam",
        "Laura"
        "Ibu nakal",
        "onani",
        "ibu",
        "Mut",
        "tinju",
        "pelacur",
        "pornografi",
        "literatur",
        "fiksasi",
        "tantangan",
        "Jada"
        "cat",
        "Persetan",
        "payudara",
        "pelacur",
        "ciuman",
        "pantat",
        "matras"
        "pekerjaan tangan",
        "anal",
        "tdk berpelana",
        "gemuk",
        "BDSM",
        "nampan dangkal",
        "seks oral",
        "Brazzer",
        "bukkake",
        "Gadis kamera",
        "Cam Hoar",
        "kokang",
        "cougar",
        "Pai Krim",
        "Suami yg istrinya tdk setia",
        "hebat",
        "Ekstrim",
        "hebat",
        "air mani",
        "gambar rusak",
        "Gadis pelacur",
        "mulut mulut",
        "Tenggorokan dalam",
        "Sangat menyebalkan",
        "dildo",
        "anjing",
        "Gaya anjing",
        "Dominatrix",
        "Kama",
        "teman",
        "femdom",
        "jari",
        "tinju",
        "gunakan kakimu",
        "Gang",
        "pekerjaan tangan",
        "Hentai",
        "terangsang",
        "Yang paling terangsang",
        "Terangsang",
        "Jisme",
        "sperma",
        "Tuan Kelelawar",
        "Silahkan",
        "onani",
        "gadis milf",
        "seks",
        "Sukaria",
        "fiksasi",
        "pornografi",
        "pornhub",
        "telanjang",
        "bintang porno",
        "Tabung Merah",
        "Memikat",
        "Dingin",
        "Menyemprotkan air",
        "mengikat",
        "Tiga orang",
        "penggetar",
        "X Hamster",
        "xnxx",
        "xvideo",
        "xxx",
        "Yuporn",
        "dildo",
        "Slot",
        "Bakarat",
        "Kasino",
        "berjudi",
        "taruhan sepakbola online",
        "taruhan sepak bola",
        "taruhan sepakbola online baru",
        "kredit gratis",
        "kredit bebas slot",
        "slot online",
        "slot hal",
        "berjudi",
        "bertaruh",
        "Bingo",
        "Rolet",
        "poker",
        "Selikuran",
        "taruhan sepak bola",
        "kredit gratis",
        "lotre",
        "Judi",
        "Mesin slot",
        "Poker",
        "Roulette",
        "Blackjack",
        "Baccarat",
        "Lotere",
        "Taruhan olahraga",
        "Judi online",
        "Taruhan bola",
        "Balap kuda",
        "Togel",
        "Ruang judi",
        "Bertaruh",
    ],
    "pt": english_flagged_words
    + [
        "balalao",
        "bate uma",
        "beijo grego",
        "boceta",
        "boquete",
        "buceta",
        "caralho",
        "chochota",
        "coito",
        "cona",
        "consolo",
        "corno",
        "cu",
        "dar a bunda",
        "dar o rabo",
        "dildo",
        "dildos",
        "esporrar",
        "estrovenga",
        "felação",
        "filho da puta",
        "filhos da puta",
        "gozada",
        "jeba",
        "perereca",
        "pica",
        "piru",
        "porno",
        "pornografia",
        "pornô",
        "porra",
        "prostituta",
        "pube",
        "punheta",
        "punheteiro",
        "putaria",
        "queca",
        "sexo",
        "siririca",
        "tesão",
        "trepada",
        "verga",
        "vibrador",
        "xana",
        "xochota",
        "xoxota",
    ],
    "ur": english_flagged_words
    + [
        "انگلی کرنا",
        "ایکس ریٹیڈ",
        "بلو جاب",
        "بٹ",
        "جھٹکا بند",
        "دلڈو",
        "رنڈی",
        "سلٹ",
        "سکلیرا",
        "سیڈسٹ",
        "سیکس بم",
        "شہوانی",
        "شہوت انگیز",
        "فحش نگاری",
        "لن",
        "لنڈ",
        "لنڈ چوسنے والا",
        "لوڑہ",
        "ماں کمینے",
        "مشت زنی",
        "ممے",
        "مٹھ",
        "مٹھی",
        "ویشیا",
        "پورن",
        "پھدی",
        "پیگنگ",
        "چدائ",
        "چدک",
        "چوت",
        "چودنا",
        "چوچی",
        "کسبی",
        "کسنگ",
        "گانڈ",
        "گدا",
        "ہینڈ جاب",
    ],
    "vi": english_flagged_words
    + [
        "cặc",
        "lồn",
        "địt",
        "buồi",
        "đụ",
        "nứng",
        "phò",
        "bú lol",
        "bú lon",
        "bú cac",
        "bú cak",
        "bú cax",
        "bú buoi",
        "bú mút",
        "húp lol",
        "húp lon",
        "húp sò",
        "nung lol",
        "nung lon",
        "nug lon",
        "nung cac",
        "nung buoi",
        "thèm dit",
        "thèm lon",
        "thèm lol",
        "thèm buoi",
        "thèm dit",
        "thèm chich",
        "thèm chịch",
        "thèm cax",
        "thèm cak",
        "móc lol",
        "móc lon",
        "buscu",
        "lol non",
        "bướm non",
        "vú to",
        "vú bự",
        "lon to",
        "phim sex",
        "phim xex",
        "phim xxx",
        "Yuph",
        "Dương vật giả",
        "Máy đánh bạc",
        "Baccarat",
        "Sòng bạc",
        "bài bạc",
        "bài bạc",
        "cá cược bóng đá trực tuyến",
        "cá cược bóng đá",
        "cá cược bóng đá trực tuyến mới",
        "tín dụng miễn phí",
        "tín dụng miễn phí khe",
        "máy đánh bạc trực tuyến",
        "khe cắm pg",
        "bài bạc",
        "Sòng bạc",
        "Máy đánh bạc",
        "cá cược",
        "Chơi lô tô",
        "Còng quay",
        "bài poker",
        "Xì dách",
        "cá cược bóng đá",
        "tín dụng miễn phí",
        "vé số",
        "Cờ bạc",
        "Sòng bạc",
        "Máy đánh bạc",
        "Poker",
        "Roulette",
        "Blackjack",
        "Baccarat",
        "Xổ số",
        "Cá cược thể thao",
        "Đánh bạc trực tuyến",
        "Cá độ bóng đá",
        "Cá độ đua ngựa",
        "Vé số",
        "Phòng đánh bạc",
        "Đặt cược",
        "tinh ranh",
        "Đã chấm điểm",
        "Con điếm",
        "mắm tôm",
        "TÔI",
        "Chết tiệt",
        "gà",
        "Âm hộ",
        "dương vật",
        "Jake",
        "Giao",
        "đĩ",
        "sợi",
        "mông",
        "vỡ nước",
        "Bạn",
        "Mẹ kiếp",
        "Mẹ kiếp",
        "Thằng khốn",
        "Làm sạch tủ lạnh",
        "gót chân",
        "động dục",
        "gây khó chịu",
        "Người phụ nữ thâm độc",
        "đổ",
        "Cái quái gì vậy",
        "Giăm bông",
        "âm hộ",
        "chết tiệt",
        "Omnokkhao",
        "Trâu",
        "tới ngón tay"
        "Xếp hạng X",
        "thổi kèn",
        "đáy",
        "Giảm sốc",
        "Dương vật giả",
        "Randy"
        "Con điếm",
        "nhút nhát"
        "sự tàn bạo",
        "Quả bom tình dục",
        "gợi cảm",
        "khiêu dâm",
        "Lin",
        "thịt gà",
        "kẻ hút gà",
        "Laura"
        "Mẹ ơi",
        "thủ dâm",
        "mẹ",
        "Muth",
        "nắm đấm",
        "gái điếm hạng sang",
        "khiêu dâm",
        "văn học",
        "cố định",
        "thử thách",
        "Jada"
        "âm hộ",
        "Mẹ kiếp",
        "ngực",
        "gái điếm hạng sang",
        "hôn",
        "mông",
        "nệm"
        "làm việc bằng tay",
        "hậu môn",
        "cởi trần",
        "mập",
        "BDSM",
        "khay nông",
        "thổi kèn",
        "Brazzers",
        "bukkake",
        "Camgirl",
        "Cẩm Hoar",
        "gà",
        "báo sư tử",
        "Bánh kem",
        "Cuckucking",
        "tuyệt vời",
        "Xuất tinh",
        "tuyệt vời",
        "kiêm",
        "hình ảnh bị hỏng",
        "Cô gái điếm",
        "miệng miệng",
        "Họng sâu",
        "Hút sâu",
        "Dương vật giả",
        "Dương vật giả",
        "chó",
        "kiểu chó",
        "Người thống trị",
        "Kama",
        "bạn",
        "nữ tính",
        "ngón tay",
        "nắm đấm",
        "dùng chân",
        "Băng nhóm",
        "làm việc bằng tay",
        "Hentai",
        "sừng",
        "Sừng nhất",
        "Sừng",
        "Jism",
        "tinh trùng",
        "Sư phụ Bát",
        "Tự lo lấy thân",
        "thủ dâm",
        "gái hư",
        "tình dục",
        "Truy hoan",
        "cố định",
        "khiêu dâm",
        "Pornhub",
        "khỏa thân",
        "ngôi sao khiêu dâm",
        "Ống đỏ",
        "Vành đai",
        "mát mẻ",
        "Phun nước",
        "dây đeo",
        "Ba người",
        "Máy rung",
        "X Hamster",
        "xnxx",
        "xvideos",
        "xxx",
        "Yuph",
        "Dương vật giả",
        "Máy đánh bạc",
        "Baccarat",
        "Sòng bạc",
        "bài bạc",
        "bài bạc",
        "cá cược bóng đá trực tuyến",
        "cá cược bóng đá",
        "cá cược bóng đá trực tuyến mới",
        "tín dụng miễn phí",
        "tín dụng miễn phí khe",
        "máy đánh bạc trực tuyến",
        "khe cắm pg",
        "cá cược",
        "Chơi lô tô",
        "Còng quay",
        "bài poker",
        "Xì dách",
        "vé số",
        "sòng bạc",
        "khe",
        "đăng nhập sòng bạc trực tiếp",
        "Baccarat trực tuyến trực tuyến",
        "trang web cờ bạc",
        "gclub miễn phí 500",
        "joker123",
        "slotxo",
        "Trò chơi đánh bạc",
        "vé số",
        "thị trường chứng khoán",
        "trò chơi cờ bạc",
        "máy đánh bạc",
        "Chào Lô",
        "Vé số",
        "cá cược bóng đá",
        "Cá cược ngựa",
        "phòng cờ bạc",
    ],
    "zh": english_flagged_words
    + [
        "三级片",
        "乳交",
        "卖B",
        "卖比",
        "卖淫",
        "口交",
        "姣西",
        "打炮",
        "打飞机",
        "抽插",
        "招妓",
        "插你",
        "插死你",
        "淫水",
        "肉壁",
        "肉棍子",
        "肉缝",
        "肏",
        "肛交",
    ],
    'th': english_flagged_words
    + [
        "กระดอ",
        "กระเด้า", 
        "กระหรี่", 
        "กะปิ", 
        "กู", 
        "ขี้", 
        "ควย", 
        "จิ๋ม", 
        "จู๋", 
        "เจ๊ก", 
        "เจี๊ยว", 
        "ดอกทอง",
        "ตอแหล", 
        "ตูด", 
        "น้ําแตก", 
        "มึง", 
        "แม่ง", 
        "เย็ด", 
        "รูตูด", 
        "ล้างตู้เย็น", 
        "ส้นตีน", 
        "สัด", 
        "เสือก", 
        "หญิงชาติชั่ว", 
        "หลั่ง", 
        "ห่า", 
        "หํา", 
        "หี", 
        "เหี้ย", 
        "อมนกเขา", 
        "ไอ้ควาย",
        "ถึงนิ้ว"
        "เรต X",
        "งานเป่า",
        "ก้น",
        "ช็อกปิด",
        "ดิลโด",
        "แรนดี้"
        "อีตัว",
        "ตาขาว"
        "ซาดิสม์",
        "เซ็กซี่",
        "สื่อลามก",
        "ลิน",
        "ไก่",
        "ไก่ดูด",
        "ลอร่า"
        "แม่สารเลว",
        "การช่วยตัวเอง",
        "แม่",
        "มุธ",
        "กำปั้น",
        "โสเภณี",
        "สื่อลามก",
        "วรรณกรรม",
        "การตรึง",
        "ท้าทาย",
        "ชฎา"
        "หี",
        "แม่ง",
        "หัวนม",
        "โสเภณี",
        "จูบ",
        "ตูด",
        "ที่นอน"
        "งานมือ",
        "ทางทวารหนัก",
        "หลังเปล่า",
        "อ้วน",
        "บีดีเอสเอ็ม",
        "ด้ง",
        "นม",
        "งานเป่า",
        "บราซเซอร์",
        "bukkake",
        "แคมเกิร์ล",
        "แคมโฮร์",
        "ไอ้จ้อน",
        "เสือภูเขา",
        "ครีมพาย",
        "สามีซึ่งภรรยามีชู้",
        "คัมมิง",
        "น้ำแตก",
        "ภาพแตก",
        "สาวร่าน",
        "ปากปาก",
        "คอลึก",
        "อมลึก",
        "ดิลโด",
        "ดิลโด้",
        "ท่าหมา",
        "โดมินาทริกซ์",
        "กาม",
        "ผู้หญิงเป็นใหญ่",
        "กำปั้น",
        "ใช้เท้า",
        "แก๊งค์",
        "งานใช้มือ",
        "เฮ็นไท",
        "มีเขา",
        "เงี่ยนที่สุด",
        "เงี่ยน",
        "จิสม์",
        "อสุจิ",
        "มาสเตอร์แบท",
        "ช่วยตัวเอง",
        "สาวรุ่นแม่",
        "เซ็กซ์",
        "สนุกสนานกันอย่างเป็นบ้าเป็นหลัง",
        "การตรึง",
        "สื่อลามก",
        "พรฮับ",
        "โป๊",
        "ดาราหนังโป๊",
        "เรดทูป",
        "ริมมิง",
        "เท่",
        "น้ำพุ่ง",
        "สายรัด",
        "สามคน",
        "เครื่องสั่น",
        "เอ็กซ์แฮมสเตอร์",
        "xnxx",
        "xvideos",
        "xxx",
        "ยูพร",
        "ดิลโด",
        "สล็อต",
        "บาคาร่า",
        "คาสิโน",
        "การพนัน",
        "พนันบอล",
        "เครดิตฟรี",
        "สล็อตออนไลน์",
        "pgslot",
        "เดิมพัน",
        "บิงโก",
        "รูเล็ต",
        "โป๊กเกอร์",
        "แบล็คแจ็ค",
        "หวย",
        "casino",
        "slots",
        "livecasino",
        "บาคาร่าออนไลน์สด",
        "เว็บพนัน",
        "gclub ฟรี 500",
        "joker123",
        "slotxo",
        "เกมสล็อต",
        "ลอตเตอรี่",
        "ตลาดหุ้น",
        "เกมส์พนัน",
        "เครื่องสล็อต",
        "ไฮโล",
        "ล็อตเตอรี่",
        "แทงบอล",
        "แทงม้า",
        "ห้องพนัน",
        "slot wallet",
        "ไบนารี่ออฟชั่น",
        "การเล่นไบนารี่ออฟชั่น",
        "ทดลองเล่นเกมส์",
        "ทดลองเล่นเครดิตฟรี",
        "ทดลองเล่นเกมสล็อตpg",
        "ทดลองเล่นค่ายpp",
        "luckygod",
        "ถ่ายเจลีกวันนี้",
        "สูตรเล่นสล็อต jokerการเดิมพัน",
        "รูเล็ตลุ้นบาท",
        "ถอนเงินจากบาคาร่าไม่ได้",
        "ufabetล่าสุด",
        "ufa955",
        "ทดลองเล่นบาคาร่าwm",
        "เล่นการพนันเสียตลอด",
        "พนันออนไลน์",
        "สูตรบาคาร่ารวยรวย",
        "สล็อต",
        "ทดลองใช้ฟรี",
        "สมัคร happyluke",
        "bet365",
        "จีคลับ888",
        "เงินฟรี500",
        "เงินฟรี",
        "slot มือถือ",
        "เจ้ามือรับแทงบอลฟุตบอ",
        "สล็อตแมชชีนเหรียญออนไลน์",
        "live22",
        "bacc6666 ",
        "slotmachine",
        "สมัครw8",
        "188bet",
        "การพนันฟุตบอล",
        "บา คา ร่า",
        "วิธี สมัคร พนัน ออนไลน์",
        "xoslot69thai",
        "บา คา ร่า7",
        "สูตร แทง ทบ บา คา ร่า",
        "ฝาก 50 รับ 150",
        "บา คา ร่า มา เก๊า",
        "คา สิ โน ประเทศ",
        "คา สิ โน ออนไลน์ มาเลเซีย",
        "mafia8",
        "บาคาร่า",
        "สล็อต",
        "ทดลองเล่น",
        "พนันออนไลน์",
        "เครดิตฟรี",
        "เล่นlsm99",
        "รวจล๊อตเตอรี่",
        "588ws",
        "โจ๊กเกอร์123th",
        "สมัครเว็บบอลฟรี",
        "หมุนวงล้อ",
        "ทีเด็ดบอลเต็ง1ตัวฟรี",
        "jokerth888",
        "ufa",
        "ทีเด็ดบอล",
        "สล็อตโจ๊กเกอร์",
        "mm88rich",
        "เว็บบอลฝากถอน100",
        "แอพdafabet",
        "แอพเล่นเกมมือถือบนคอม",
        "เว็บเกมได้ตัง",
        "918kiss",
        "แคนดี้ป๊อปได้เงินจริง",
        "เล่นเกมแล้วได้เงินจริงหรอ",
        "แจกเคดิตฟรีล่าสุด",
        "เล่นเกมส์จับผิด",
        "ยิงปลามือถือ",
        "ยิงปลายังไงให้ได้ตัง",
        "ยูฟ่า888",
        "รับฟรีเครดิต100",
        "lsm99",
        "วิธีการเล่นน้ำเต้าปูปลา",
        "วิธีซื้อสลากกินแบ่งรัฐบาล",
        "panda777",
        "วิเคราะห์บอล",
        "ราคาบอลไหล",
    ],
    'lo': english_flagged_words
    + [
         "ຮູບເງົາຊັ້ນສູງ",
         "Titty Fuck",
         "ຂາຍ B",
         "ອັດຕາສ່ວນການຂາຍ",
         "ໂສເພນີ",
         "ການຮ່ວມເພດທາງປາກ",
         "ຈ່າໂອຊີ",
         "ຍິງ",
         "ກະຕືລືລົ້ນ",
         "ຍູ້",
         "ຮັບສະໝັກໂສເພນີ",
         "ໃສ່ເຈົ້າ",
         "Fuck ເຈົ້າຕາຍ",
         "ຄວາມລັບທາງເພດ",
         "ຝາເນື້ອຫນັງ",
         "ຊີ້ນງົວ",
         "ແກະຊີ້ນ",
         "ຟັກ",
         "ການຮ່ວມເພດທາງຮູທະວານ",
         "ເປັດ",
         "ໃຫ້ຄະແນນ",
         "ໂສເພນີ",
         "ກຸ້ງ",
         "ຂ້ອຍ",
         "ຊິ",
         "ໄກ່",
         "ຫີ",
         "ອະໄວຍະວະ",
         "ເຈກ",
         "ຈ່າວ",
         "ປາງ",
         "fib",
         "ກົ້ນ",
         "ພັກຜ່ອນນ້ໍາ",
         "ເຈົ້າ",
         "ຟັກ",
         "ກົ້ນ",
         "ເຮັດຄວາມສະອາດຕູ້ເຢັນ",
         "ສົ້ນຕີນ",
         "estrus",
         "ຂີ້ຄ້ານ",
         "ຜູ້ຍິງຊົ່ວ",
         "ຖອກ",
         "ເປັນຈັ່ງໃດ",
         "ແຮມ",
         "ຫີ",
         "ສາບແຊ່ງ",
         "ຄວາຍ",
         "ກັບນິ້ວມື",
         "ຄະແນນ X",
         "ງານລະເບີດ",
         "ກົ້ນ",
         "ຕົກໃຈ",
         "dildo",
         "Randy",
         "ສະຫຼັດ",
         "Sclera",
         "Sadist",
         "ລະເບີດທາງເພດ",
         "ເຊັກຊີ່",
         "ເຊັກຊີ່",
         "ຮູບພາບລາມົກ",
         "ລິນ",
         "ໄກ່",
         "ດູດໄກ່",
         "ໂລຣາ",
         "ແມ່ຕູ້",
         "Masturbation",
         "ແມ່",
         "ມູດ",
         "ກຳປັ້ນ",
         "ໂສເພນີ",
         "ຄອມ",
         "ວັນນະຄະດີ",
         "ປັກກິ້ງ",
         "ສິ່ງທ້າທາຍ",
         "ຊາດາກ",
         "ຫີ",
         "fuck",
         "ຫົວນົມ",
         "ໂສເພນີ",
         "ຈູບ",
         "ກົ້ນ",
         "ທີ່ນອນ",
         "ວຽກມື",
         "ຍຸພອນ",
         "Dildo",
         "ສະລັອດຕິງ",
         "Baccarat",
         "ຄາສິໂນ",
         "ການພະນັນ",
         "ການພະນັນ",
         "ການພະນັນບານເຕະອອນໄລນ໌",
         "ການພະນັນບານເຕະ",
         "ການພະນັນບານເຕະອອນໄລນ໌ໃຫມ່",
         "ສິນເຊື່ອຟຣີ",
         "ສິນເຊື່ອຟຣີສະລັອດຕິງ",
         "ສະລັອດຕິງອອນໄລນ໌",
         "pg slot",
         "ການພະນັນ",
         "ຄາສິໂນ",
         "ສະລັອດຕິງ",
         "ເດີມພັນ",
         "ບິງໂກ",
         "Roulette",
         "ໂປ໊ກເກີ",
         "Blackjack",
         "ການພະນັນບານເຕະ",
         "ສິນເຊື່ອຟຣີ",
         "ຫວຍ",
         "ເດີມພັນ",
    ],
    'ms': english_flagged_words+
    [
        "Filem Teratas",
        "Titty Fuck",
        "Jual B",
        "nisbah jualan",
        "pelacur",
        "seks oral",
        "Cik Ozzy",
        "perempuan",
        "bersemangat",
        "tolak",
        "merekrut pelacur",
        "pakai awak",
        "Matilah awak",
        "rahsia seksual",
        "dinding daging",
        "daging lembu",
        "kulit daging",
        "cincang",
        "seks dubur",
        "itik",
        "kadar",
        "pelacur",
        "udang",
        "saya",
        "Shh",
        "ayam",
        "neraka",
        "organ",
        "Jek",
        "hijau",
        "Pang",
        "fib",
        "punggung",
        "pecah air",
        "awak",
        "cincang",
        "punggung",
        "bersihkan peti ais",
        "tumit",
        "estrus",
        "malas",
        "Wanita Jahat",
        "tuang",
        "Apa khabar",
        "Ham",
        "neraka",
        "kutukan",
        "ideal",
        "kerbau",
        "dengan jari",
        "Skor X",
        "Letupan",
        "punggung",
        "terkejut",
        "dildo",
        "Randy",
        "salad",
        "Sclera",
        "Sadis",
        "bom seks",
        "seksi",
        "seksi",
        "lucah",
        "Lin",
        "ayam",
        "hisap ayam",
        "Laura",
        "Nenek",
        "Melancap",
        "ibu",
        "Lumpur",
        "penumbuk",
        "pelacur",
        "com",
        "Sastera",
        "Peking",
        "Cabaran",
        "Sadak",
        "neraka",
        "sial",
        "puting",
        "pelacur",
        "cium",
        "punggung",
        "katil",
        "kerja tangan",
        "Yuporn",
        "Dildo",
        "Slot",
        "Baccarat",
        "Kasino",
        "perjudian",
        "perjudian",
        "pertaruhan bola sepak dalam talian",
        "pertaruhan bola sepak",
        "pertaruhan bola sepak dalam talian baharu",
        "kredit percuma",
        "kredit percuma slot",
        "slot dalam talian",
        "slot pg",
        "perjudian",
        "Kasino",
        "Slot",
        "taruhan",
        "Bingo",
        "Roulette",
        "poker",
        "Blackjack",
        "pertaruhan bola sepak",
        "kredit percuma",
        "loteri",
        "taruhan",
    ],
}
